MAGE-957: js and css reorged.
algolia/algoliasearch-custom-algolia-magento-2 pull request #11
Opened 2024-08-02 20:09 UTC by mrahman3177

js and css reorganized.

2024-08-05 12:26 UTC, damcou requested changes
Looks fine !
Maybe we should put the `autocomplete-plugin-recent-searches.js` file in an `internals` folder as we did in the extension ? WDYT ?

2024-08-05 13:10 UTC, mrahman3177 commented
That's a good idea to be consistent. Thanks for pointing it out.

2024-08-05 14:18 UTC, damcou approved these changes
LGTM

2024-08-12 14:44 UTC, cammonro requested changes
@mrahman3177 Let's bump this to version 1.3 and tag it with a `^3.14.0` dependency on the main module `algolia/algoliasearch-magento-2`.

2024-08-12 19:34 UTC, cammonro requested changes
@mrahman3177  Let's be sure to bump the version whenever we merge to master. I'm thinking we should bump by a minor version for every minor version in the main extension. `1.3.0` since we just released `3.14.0`. WDYT?

2024-08-12 19:34 UTC, cammonro commented on composer.json
>    "version": "1.2.2",
```suggestion
  "version": "1.3.0",
```

2024-08-13 13:56 UTC, cammonro approved these changes

2024-08-13 15:00 UTC, merged